INSERT INTO pets (name, species, age, breed, gender, status) VALUES
('Harper', 'Rabbit', 9, 'Golden Retriever', 'Female', 'Sold'),
('Bailey', 'Cat', 7, 'Beagle', 'Female', 'Sold'),
('Marley', 'Bird', 4, 'Bulldog', 'Female', 'Available'),
('Finn', 'Dog', 3, 'Parrot', 'Male', 'Available'),
('Hazel', 'Dog', 7, 'Poodle', 'Female', 'Available'),
('Poppy', 'Dog', 10, 'Persian', 'Female', 'Sold'),
('Nala', 'Rabbit', 8, 'Siamese', 'Female', 'Available'),
('Pepper', 'Dog', 2, 'Beagle', 'Male', 'Under Treatment'),
('Lily', 'Bird', 4, 'Golden Retriever', 'Female', 'Sold'),
('Ginger', 'Dog', 10, 'Poodle', 'Female', 'Sold'),
('Koda', 'Cat', 3, 'Parrot', 'Male', 'Sold'),
('Blue', 'Rabbit', 1, 'Parrot', 'Female', 'Sold'),
('Marley', 'Rabbit', 5, 'Siamese', 'Female', 'Under Treatment'),
('Teddy', 'Rabbit', 5, 'Labrador', 'Female', 'Sold'),
('Oreo', 'Dog', 4, 'Canary', 'Male', 'Sold'),
('Tucker', 'Dog', 8, 'Bulldog', 'Female', 'Sold'),
('Poppy', 'Bird', 4, 'Persian', 'Female', 'Sold'),
('Oreo', 'Rabbit', 8, 'Bulldog', 'Male', 'Under Treatment'),
('Hunter', 'Cat', 8, 'Canary', 'Male', 'Available'),
('Tucker', 'Rabbit', 5, 'Holland Lop', 'Male', 'Sold'),
('Hazel', 'Cat', 8, 'Persian', 'Male', 'Available'),
('Hazel', 'Cat', 4, 'Beagle', 'Female', 'Under Treatment'),
('Bandit', 'Dog', 1, 'Siamese', 'Male', 'Available'),
('Pepper', 'Rabbit', 8, 'Poodle', 'Female', 'Sold'),
('Lily', 'Rabbit', 4, 'Labrador', 'Female', 'Under Treatment'),
('Sadie', 'Bird', 4, 'Bulldog', 'Female', 'Available'),
('Harper', 'Dog', 8, 'Golden Retriever', 'Female', 'Under Treatment'),
('Nala', 'Bird', 1, 'Canary', 'Female', 'Under Treatment'),
('Hunter', 'Cat', 8, 'Poodle', 'Male', 'Sold'),
('Stella', 'Rabbit', 8, 'Holland Lop', 'Female', 'Sold'),
('Hunter', 'Bird', 5, 'Holland Lop', 'Male', 'Sold'),
('Finn', 'Bird', 9, 'Beagle', 'Male', 'Available'),
('Diesel', 'Dog', 5, 'Persian', 'Female', 'Under Treatment'),
('Ellie', 'Cat', 1, 'Poodle', 'Male', 'Available'),
('Ellie', 'Dog', 5, 'Holland Lop', 'Female', 'Available'),
('Poppy', 'Cat', 2, 'Beagle', 'Male', 'Under Treatment'),
('Sadie', 'Rabbit', 9, 'Poodle', 'Female', 'Available'),
('Pepper', 'Rabbit', 7, 'Labrador', 'Female', 'Sold'),
('Bandit', 'Cat', 9, 'Labrador', 'Female', 'Available'),
('Hazel', 'Cat', 3, 'Golden Retriever', 'Female', 'Available'),
('Marley', 'Cat', 1, 'Siamese', 'Female', 'Under Treatment'),
('Ellie', 'Dog', 3, 'Labrador', 'Male', 'Sold'),
('Ellie', 'Bird', 3, 'Canary', 'Male', 'Available'),
('Bailey', 'Dog', 6, 'Bulldog', 'Male', 'Available'),
('Finn', 'Bird', 4, 'Bulldog', 'Female', 'Under Treatment'),
('Scout', 'Dog', 5, 'Labrador', 'Male', 'Under Treatment'),
('Ginger', 'Cat', 7, 'Persian', 'Male', 'Sold'),
('Harper', 'Cat', 7, 'Labrador', 'Female', 'Sold'),
('Scout', 'Rabbit', 4, 'Holland Lop', 'Female', 'Under Treatment'),
('Cleo', 'Rabbit', 5, 'Canary', 'Female', 'Sold'),
('Moose', 'Cat', 1, 'Parrot', 'Female', 'Available'),
('Chloe', 'Bird', 10, 'Golden Retriever', 'Male', 'Sold'),
('Moose', 'Dog', 2, 'Parrot', 'Female', 'Available'),
('Marley', 'Rabbit', 6, 'Canary', 'Female', 'Available'),
('Bailey', 'Cat', 4, 'Poodle', 'Male', 'Available'),
('Hunter', 'Dog', 3, 'Siamese', 'Female', 'Under Treatment'),
('Dash', 'Rabbit', 6, 'Beagle', 'Female', 'Under Treatment'),
('Blue', 'Dog', 4, 'Parrot', 'Male', 'Under Treatment'),
('Dash', 'Cat', 10, 'Poodle', 'Female', 'Available'),
('Dash', 'Dog', 8, 'Siamese', 'Male', 'Available'),
('Ginger', 'Bird', 7, 'Canary', 'Male', 'Available'),
('Stella', 'Bird', 2, 'Bulldog', 'Male', 'Sold'),
('Ellie', 'Bird', 5, 'Poodle', 'Female', 'Available'),
('Milo', 'Bird', 9, 'Parrot', 'Female', 'Under Treatment'),
('Stella', 'Cat', 9, 'Beagle', 'Female', 'Under Treatment'),
('Hunter', 'Dog', 5, 'Bulldog', 'Female', 'Sold'),
('Hazel', 'Cat', 9, 'Canary', 'Male', 'Sold'),
('Ginger', 'Cat', 4, 'Parrot', 'Female', 'Sold'),
('Cleo', 'Rabbit', 9, 'Labrador', 'Male', 'Sold'),
('Hazel', 'Bird', 6, 'Siamese', 'Male', 'Under Treatment'),
('Scout', 'Bird', 3, 'Bulldog', 'Male', 'Under Treatment'),
('Koda', 'Dog', 4, 'Labrador', 'Female', 'Sold'),
('Stella', 'Dog', 8, 'Beagle', 'Male', 'Sold'),
('Marley', 'Bird', 5, 'Poodle', 'Male', 'Under Treatment'),
('Dexter', 'Rabbit', 9, 'Canary', 'Male', 'Sold'),
('Moose', 'Dog', 3, 'Golden Retriever', 'Female', 'Under Treatment'),
('Koda', 'Rabbit', 7, 'Labrador', 'Male', 'Available'),
('Rosie', 'Bird', 2, 'Bulldog', 'Female', 'Sold'),
('Hunter', 'Dog', 7, 'Siamese', 'Male', 'Available'),
('Marley', 'Bird', 5, 'Holland Lop', 'Male', 'Under Treatment'),
('Pepper', 'Cat', 4, 'Labrador', 'Female', 'Under Treatment'),
('Ellie', 'Bird', 6, 'Holland Lop', 'Male', 'Under Treatment'),
('Finn', 'Dog', 4, 'Persian', 'Female', 'Sold'),
('Hazel', 'Rabbit', 10, 'Beagle', 'Male', 'Sold'),
('Rosie', 'Dog', 9, 'Parrot', 'Male', 'Under Treatment'),
('Oreo', 'Dog', 4, 'Golden Retriever', 'Female', 'Sold'),
('Nala', 'Bird', 3, 'Siamese', 'Male', 'Available'),
('Ellie', 'Dog', 7, 'Poodle', 'Male', 'Available'),
('Blue', 'Cat', 7, 'Poodle', 'Male', 'Sold'),
('Rosie', 'Dog', 4, 'Bulldog', 'Male', 'Sold'),
('Milo', 'Rabbit', 2, 'Labrador', 'Female', 'Available'),
('Milo', 'Rabbit', 2, 'Poodle', 'Female', 'Available'),
('Ginger', 'Cat', 9, 'Bulldog', 'Male', 'Under Treatment'),
('Bandit', 'Rabbit', 6, 'Labrador', 'Male', 'Under Treatment'),
('Lily', 'Dog', 1, 'Holland Lop', 'Male', 'Under Treatment'),
('Tucker', 'Cat', 4, 'Labrador', 'Female', 'Under Treatment'),
('Koda', 'Rabbit', 9, 'Bulldog', 'Female', 'Sold'),
('Tucker', 'Rabbit', 7, 'Labrador', 'Female', 'Sold'),
('Cleo', 'Dog', 2, 'Poodle', 'Female', 'Under Treatment'),
('Dexter', 'Bird', 5, 'Siamese', 'Male', 'Available'),
('Dexter', 'Bird', 10, 'Siamese', 'Male', 'Sold'),
('Ruby', 'Cat', 2, 'Siamese', 'Male', 'Available'),
('Rosie', 'Dog', 9, 'Canary', 'Male', 'Sold'),
('Diesel', 'Cat', 3, 'Parrot', 'Female', 'Sold'),
('Moose', 'Bird', 5, 'Parrot', 'Male', 'Sold'),
('Cleo', 'Dog', 4, 'Beagle', 'Male', 'Sold'),
('Harper', 'Bird', 9, 'Poodle', 'Female', 'Available'),
('Oreo', 'Rabbit', 6, 'Golden Retriever', 'Female', 'Under Treatment'),
('Scout', 'Cat', 9, 'Golden Retriever', 'Female', 'Sold'),
('Bailey', 'Rabbit', 4, 'Siamese', 'Female', 'Sold'),
('Pepper', 'Dog', 9, 'Holland Lop', 'Female', 'Available'),
('Lily', 'Dog', 8, 'Canary', 'Female', 'Sold'),
('Sadie', 'Rabbit', 7, 'Bulldog', 'Male', 'Under Treatment'),
('Dexter', 'Rabbit', 9, 'Bulldog', 'Male', 'Under Treatment'),
('Finn', 'Bird', 4, 'Beagle', 'Female', 'Available'),
('Bailey', 'Dog', 10, 'Canary', 'Male', 'Available'),
('Chloe', 'Dog', 6, 'Beagle', 'Female', 'Under Treatment'),
('Hazel', 'Dog', 9, 'Bulldog', 'Male', 'Under Treatment'),
('Pepper', 'Bird', 1, 'Canary', 'Male', 'Under Treatment'),
('Dexter', 'Dog', 7, 'Holland Lop', 'Male', 'Under Treatment'),
('Dash', 'Rabbit', 3, 'Bulldog', 'Female', 'Under Treatment'),
('Oreo', 'Cat', 1, 'Bulldog', 'Female', 'Under Treatment'),
('Hunter', 'Dog', 9, 'Beagle', 'Female', 'Under Treatment'),
('Koda', 'Dog', 8, 'Poodle', 'Male', 'Sold'),
('Diesel', 'Bird', 5, 'Persian', 'Male', 'Available'),
('Hunter', 'Cat', 1, 'Persian', 'Female', 'Available'),
('Teddy', 'Cat', 3, 'Bulldog', 'Female', 'Available'),
('Lily', 'Cat', 2, 'Holland Lop', 'Male', 'Under Treatment'),
('Nala', 'Dog', 8, 'Parrot', 'Female', 'Under Treatment'),
('Hazel', 'Rabbit', 10, 'Bulldog', 'Female', 'Sold'),
('Koda', 'Rabbit', 7, 'Beagle', 'Female', 'Under Treatment'),
('Blue', 'Cat', 10, 'Golden Retriever', 'Female', 'Under Treatment'),
('Dexter', 'Bird', 9, 'Golden Retriever', 'Male', 'Under Treatment'),
('Tucker', 'Cat', 7, 'Bulldog', 'Male', 'Under Treatment'),
('Bandit', 'Dog', 9, 'Poodle', 'Female', 'Under Treatment'),
('Stella', 'Dog', 2, 'Labrador', 'Male', 'Available'),
('Harper', 'Dog', 8, 'Poodle', 'Male', 'Under Treatment'),
('Blue', 'Cat', 4, 'Beagle', 'Female', 'Sold'),
('Bailey', 'Dog', 3, 'Beagle', 'Female', 'Available'),
('Ginger', 'Rabbit', 5, 'Bulldog', 'Male', 'Under Treatment'),
('Finn', 'Rabbit', 6, 'Persian', 'Male', 'Under Treatment'),
('Poppy', 'Bird', 1, 'Golden Retriever', 'Male', 'Sold'),
('Hazel', 'Dog', 4, 'Labrador', 'Female', 'Available'),
('Hunter', 'Cat', 4, 'Poodle', 'Male', 'Sold'),
('Diesel', 'Rabbit', 4, 'Labrador', 'Female', 'Available'),
('Poppy', 'Rabbit', 6, 'Persian', 'Male', 'Available'),
('Hunter', 'Cat', 10, 'Golden Retriever', 'Female', 'Sold'),
('Hunter', 'Rabbit', 8, 'Siamese', 'Male', 'Sold'),
('Tucker', 'Bird', 5, 'Labrador', 'Male', 'Under Treatment'),
('Scout', 'Bird', 7, 'Parrot', 'Female', 'Available'),
('Oreo', 'Cat', 8, 'Canary', 'Female', 'Sold'),
('Koda', 'Dog', 9, 'Labrador', 'Male', 'Sold'),
('Lily', 'Dog', 10, 'Holland Lop', 'Female', 'Available'),
('Poppy', 'Dog', 10, 'Siamese', 'Female', 'Sold'),
('Rosie', 'Rabbit', 7, 'Persian', 'Male', 'Under Treatment'),
('Moose', 'Cat', 8, 'Golden Retriever', 'Female', 'Available'),
('Teddy', 'Rabbit', 2, 'Labrador', 'Male', 'Sold'),
('Teddy', 'Dog', 4, 'Poodle', 'Male', 'Sold'),
('Harper', 'Dog', 6, 'Siamese', 'Male', 'Sold'),
('Dexter', 'Rabbit', 6, 'Siamese', 'Female', 'Available'),
('Teddy', 'Rabbit', 9, 'Beagle', 'Male', 'Under Treatment'),
('Bailey', 'Dog', 7, 'Golden Retriever', 'Female', 'Under Treatment'),
('Stella', 'Dog', 7, 'Beagle', 'Male', 'Sold'),
('Bandit', 'Bird', 4, 'Poodle', 'Male', 'Available'),
('Poppy', 'Bird', 2, 'Bulldog', 'Female', 'Available'),
('Nala', 'Cat', 8, 'Beagle', 'Female', 'Sold'),
('Bandit', 'Bird', 3, 'Siamese', 'Male', 'Available'),
('Milo', 'Rabbit', 6, 'Bulldog', 'Female', 'Available'),
('Stella', 'Dog', 10, 'Persian', 'Male', 'Sold'),
('Ellie', 'Rabbit', 2, 'Siamese', 'Female', 'Available'),
('Pepper', 'Cat', 8, 'Beagle', 'Female', 'Under Treatment'),
('Poppy', 'Rabbit', 10, 'Parrot', 'Male', 'Available'),
('Ginger', 'Rabbit', 10, 'Golden Retriever', 'Male', 'Under Treatment'),
('Blue', 'Dog', 7, 'Parrot', 'Female', 'Sold'),
('Milo', 'Cat', 3, 'Parrot', 'Female', 'Sold'),
('Harper', 'Cat', 2, 'Canary', 'Male', 'Under Treatment'),
('Oreo', 'Bird', 5, 'Canary', 'Female', 'Sold'),
('Milo', 'Bird', 7, 'Holland Lop', 'Female', 'Under Treatment'),
('Marley', 'Cat', 4, 'Parrot', 'Female', 'Sold'),
('Blue', 'Dog', 6, 'Poodle', 'Female', 'Available'),
('Rosie', 'Bird', 4, 'Golden Retriever', 'Female', 'Under Treatment'),
('Bailey', 'Bird', 3, 'Persian', 'Female', 'Under Treatment'),
('Ellie', 'Bird', 6, 'Holland Lop', 'Male', 'Under Treatment'),
('Moose', 'Dog', 10, 'Persian', 'Male', 'Sold'),
('Lily', 'Cat', 7, 'Holland Lop', 'Female', 'Sold'),
('Marley', 'Cat', 10, 'Beagle', 'Male', 'Available'),
('Koda', 'Bird', 2, 'Canary', 'Male', 'Available'),
('Dexter', 'Bird', 1, 'Golden Retriever', 'Female', 'Available'),
('Nala', 'Bird', 7, 'Siamese', 'Female', 'Available'),
('Sadie', 'Dog', 6, 'Golden Retriever', 'Female', 'Under Treatment'),
('Ruby', 'Rabbit', 6, 'Siamese', 'Female', 'Sold'),
('Nala', 'Cat', 3, 'Golden Retriever', 'Female', 'Available'),
('Koda', 'Dog', 2, 'Siamese', 'Male', 'Under Treatment'),
('Lily', 'Dog', 5, 'Parrot', 'Male', 'Sold'),
('Chloe', 'Cat', 7, 'Persian', 'Female', 'Under Treatment'),
('Blue', 'Cat', 5, 'Canary', 'Male', 'Sold'),
('Rosie', 'Rabbit', 2, 'Labrador', 'Male', 'Sold'),
('Rosie', 'Cat', 8, 'Persian', 'Male', 'Sold'),
('Harper', 'Rabbit', 6, 'Beagle', 'Male', 'Available'),
('Chloe', 'Bird', 4, 'Bulldog', 'Female', 'Sold'),
('Ginger', 'Bird', 3, 'Holland Lop', 'Female', 'Available'),
('Stella', 'Cat', 6, 'Siamese', 'Male', 'Under Treatment'),
('Finn', 'Bird', 8, 'Golden Retriever', 'Female', 'Available'),
('Diesel', 'Dog', 3, 'Parrot', 'Male', 'Under Treatment'),
('Dash', 'Rabbit', 7, 'Labrador', 'Male', 'Available'),
('Stella', 'Dog', 4, 'Beagle', 'Male', 'Under Treatment'),
('Bailey', 'Bird', 6, 'Poodle', 'Female', 'Available'),
('Scout', 'Cat', 8, 'Golden Retriever', 'Male', 'Under Treatment'),
('Ginger', 'Rabbit', 2, 'Canary', 'Female', 'Sold'),
('Lily', 'Rabbit', 3, 'Canary', 'Male', 'Sold'),
('Lily', 'Dog', 4, 'Beagle', 'Female', 'Available'),
('Cleo', 'Rabbit', 8, 'Holland Lop', 'Female', 'Available'),
('Tucker', 'Rabbit', 3, 'Bulldog', 'Male', 'Available'),
('Koda', 'Bird', 8, 'Bulldog', 'Male', 'Sold'),
('Diesel', 'Dog', 1, 'Siamese', 'Female', 'Under Treatment'),
('Ruby', 'Rabbit', 5, 'Golden Retriever', 'Male', 'Under Treatment'),
('Milo', 'Dog', 5, 'Parrot', 'Female', 'Sold'),
('Hunter', 'Cat', 5, 'Persian', 'Male', 'Sold'),
('Nala', 'Dog', 4, 'Canary', 'Male', 'Under Treatment'),
('Chloe', 'Rabbit', 8, 'Labrador', 'Male', 'Sold'),
('Ellie', 'Rabbit', 6, 'Canary', 'Male', 'Sold'),
('Lily', 'Bird', 5, 'Canary', 'Female', 'Sold'),
('Chloe', 'Cat', 4, 'Holland Lop', 'Male', 'Available'),
('Oreo', 'Cat', 7, 'Canary', 'Female', 'Sold'),
('Harper', 'Rabbit', 7, 'Beagle', 'Female', 'Available'),
('Marley', 'Bird', 10, 'Persian', 'Female', 'Sold'),
('Marley', 'Rabbit', 5, 'Parrot', 'Male', 'Sold'),
('Blue', 'Bird', 6, 'Bulldog', 'Female', 'Under Treatment'),
('Scout', 'Cat', 1, 'Beagle', 'Male', 'Under Treatment'),
('Bandit', 'Cat', 1, 'Canary', 'Male', 'Available'),
('Tucker', 'Rabbit', 2, 'Persian', 'Male', 'Available'),
('Hazel', 'Rabbit', 5, 'Siamese', 'Male', 'Sold'),
('Tucker', 'Dog', 6, 'Persian', 'Male', 'Sold'),
('Finn', 'Cat', 2, 'Poodle', 'Male', 'Available'),
('Chloe', 'Cat', 2, 'Poodle', 'Male', 'Available'),
('Oreo', 'Cat', 3, 'Golden Retriever', 'Male', 'Under Treatment'),
('Harper', 'Bird', 9, 'Bulldog', 'Female', 'Sold'),
('Dexter', 'Bird', 9, 'Beagle', 'Male', 'Under Treatment'),
('Dexter', 'Dog', 5, 'Holland Lop', 'Male', 'Under Treatment'),
('Teddy', 'Rabbit', 9, 'Bulldog', 'Female', 'Under Treatment'),
('Tucker', 'Rabbit', 1, 'Siamese', 'Male', 'Sold'),
('Hunter', 'Cat', 8, 'Siamese', 'Male', 'Available'),
('Hunter', 'Rabbit', 3, 'Parrot', 'Female', 'Sold'),
('Ruby', 'Bird', 8, 'Golden Retriever', 'Female', 'Under Treatment'),
('Bailey', 'Dog', 6, 'Bulldog', 'Female', 'Available'),
('Blue', 'Cat', 8, 'Persian', 'Female', 'Under Treatment'),
('Bailey', 'Dog', 5, 'Holland Lop', 'Female', 'Available'),
('Chloe', 'Bird', 6, 'Bulldog', 'Female', 'Under Treatment'),
('Milo', 'Rabbit', 2, 'Canary', 'Male', 'Sold'),
('Scout', 'Dog', 5, 'Bulldog', 'Female', 'Sold'),
('Oreo', 'Dog', 4, 'Bulldog', 'Male', 'Sold'),
('Poppy', 'Bird', 8, 'Parrot', 'Female', 'Sold'),
('Dexter', 'Bird', 9, 'Golden Retriever', 'Male', 'Under Treatment'),
('Bandit', 'Dog', 4, 'Persian', 'Female', 'Available'),
('Rosie', 'Cat', 1, 'Golden Retriever', 'Male', 'Available'),
('Nala', 'Rabbit', 5, 'Parrot', 'Male', 'Under Treatment'),
('Hunter', 'Dog', 9, 'Siamese', 'Female', 'Available'),
('Hunter', 'Cat', 5, 'Poodle', 'Female', 'Available'),
('Teddy', 'Cat', 1, 'Golden Retriever', 'Female', 'Under Treatment'),
('Dash', 'Rabbit', 3, 'Beagle', 'Female', 'Under Treatment'),
('Dash', 'Rabbit', 8, 'Parrot', 'Male', 'Available'),
('Blue', 'Rabbit', 3, 'Bulldog', 'Female', 'Sold'),
('Marley', 'Bird', 9, 'Persian', 'Female', 'Available'),
('Bandit', 'Cat', 6, 'Labrador', 'Female', 'Under Treatment'),
('Ruby', 'Dog', 4, 'Labrador', 'Male', 'Available'),
('Teddy', 'Bird', 8, 'Persian', 'Male', 'Under Treatment'),
('Rosie', 'Rabbit', 7, 'Golden Retriever', 'Male', 'Available'),
('Hazel', 'Rabbit', 8, 'Persian', 'Female', 'Under Treatment'),
('Ginger', 'Cat', 8, 'Persian', 'Female', 'Under Treatment'),
('Ellie', 'Bird', 7, 'Labrador', 'Female', 'Available'),
('Ginger', 'Bird', 1, 'Canary', 'Male', 'Under Treatment'),
('Scout', 'Cat', 5, 'Parrot', 'Female', 'Under Treatment'),
('Pepper', 'Dog', 9, 'Beagle', 'Female', 'Available'),
('Hunter', 'Bird', 9, 'Persian', 'Female', 'Sold'),
('Poppy', 'Dog', 10, 'Canary', 'Female', 'Under Treatment'),
('Marley', 'Dog', 2, 'Bulldog', 'Male', 'Under Treatment'),
('Teddy', 'Dog', 7, 'Siamese', 'Male', 'Sold'),
('Sadie', 'Rabbit', 5, 'Labrador', 'Female', 'Under Treatment'),
('Chloe', 'Rabbit', 6, 'Bulldog', 'Female', 'Available'),
('Blue', 'Bird', 4, 'Siamese', 'Female', 'Under Treatment'),
('Chloe', 'Dog', 5, 'Holland Lop', 'Female', 'Sold'),
('Marley', 'Rabbit', 9, 'Labrador', 'Male', 'Sold'),
('Bandit', 'Rabbit', 6, 'Beagle', 'Male', 'Sold'),
('Sadie', 'Cat', 1, 'Siamese', 'Female', 'Available'),
('Ellie', 'Bird', 4, 'Labrador', 'Male', 'Available'),
('Tucker', 'Cat', 8, 'Holland Lop', 'Female', 'Available'),
('Pepper', 'Cat', 9, 'Poodle', 'Female', 'Available'),
('Moose', 'Bird', 7, 'Siamese', 'Male', 'Sold'),
('Hazel', 'Bird', 8, 'Poodle', 'Female', 'Sold'),
('Koda', 'Dog', 7, 'Persian', 'Male', 'Available'),
('Tucker', 'Dog', 4, 'Labrador', 'Female', 'Sold'),
('Rosie', 'Bird', 2, 'Beagle', 'Female', 'Sold'),
('Tucker', 'Dog', 10, 'Canary', 'Male', 'Under Treatment'),
('Dexter', 'Cat', 1, 'Parrot', 'Female', 'Under Treatment'),
('Tucker', 'Rabbit', 6, 'Poodle', 'Female', 'Available'),
('Koda', 'Bird', 2, 'Persian', 'Male', 'Sold'),
('Rosie', 'Bird', 3, 'Persian', 'Female', 'Available'),
('Ruby', 'Dog', 3, 'Siamese', 'Female', 'Available'),
('Marley', 'Cat', 3, 'Parrot', 'Male', 'Under Treatment'),
('Cleo', 'Bird', 5, 'Bulldog', 'Female', 'Under Treatment'),
('Bailey', 'Bird', 6, 'Holland Lop', 'Female', 'Available'),
('Chloe', 'Dog', 1, 'Beagle', 'Male', 'Under Treatment'),
('Hazel', 'Rabbit', 2, 'Bulldog', 'Female', 'Under Treatment'),
('Bailey', 'Cat', 8, 'Poodle', 'Male', 'Available'),
('Stella', 'Bird', 3, 'Siamese', 'Male', 'Available'),
('Dash', 'Cat', 6, 'Holland Lop', 'Male', 'Under Treatment'),
('Moose', 'Rabbit', 3, 'Poodle', 'Male', 'Available'),
('Tucker', 'Rabbit', 9, 'Parrot', 'Male', 'Under Treatment'),
('Oreo', 'Cat', 6, 'Parrot', 'Female', 'Sold'),
('Moose', 'Dog', 5, 'Persian', 'Male', 'Sold'),
('Marley', 'Rabbit', 5, 'Beagle', 'Female', 'Sold'),
('Ginger', 'Cat', 8, 'Persian', 'Female', 'Available'),
('Moose', 'Bird', 9, 'Siamese', 'Female', 'Sold'),
('Dash', 'Cat', 9, 'Siamese', 'Male', 'Sold'),
('Teddy', 'Rabbit', 4, 'Parrot', 'Male', 'Sold'),
('Bailey', 'Dog', 10, 'Persian', 'Male', 'Sold'),
('Dexter', 'Rabbit', 10, 'Siamese', 'Female', 'Under Treatment'),
('Milo', 'Dog', 5, 'Parrot', 'Male', 'Sold'),
('Bandit', 'Cat', 7, 'Golden Retriever', 'Female', 'Available'),
('Ginger', 'Rabbit', 4, 'Poodle', 'Female', 'Sold'),
('Pepper', 'Bird', 3, 'Holland Lop', 'Female', 'Under Treatment'),
('Rosie', 'Dog', 2, 'Siamese', 'Male', 'Sold'),
('Lily', 'Bird', 9, 'Holland Lop', 'Female', 'Available'),
('Scout', 'Dog', 2, 'Persian', 'Male', 'Sold'),
('Marley', 'Rabbit', 8, 'Bulldog', 'Female', 'Under Treatment'),
('Pepper', 'Bird', 2, 'Parrot', 'Female', 'Available'),
('Moose', 'Dog', 1, 'Bulldog', 'Female', 'Available'),
('Cleo', 'Cat', 1, 'Persian', 'Female', 'Under Treatment'),
('Dexter', 'Cat', 9, 'Persian', 'Male', 'Available'),
('Finn', 'Bird', 5, 'Labrador', 'Female', 'Under Treatment'),
('Ruby', 'Dog', 1, 'Golden Retriever', 'Male', 'Sold'),
('Bailey', 'Bird', 9, 'Canary', 'Male', 'Available'),
('Ellie', 'Bird', 6, 'Parrot', 'Male', 'Sold'),
('Cleo', 'Bird', 4, 'Persian', 'Male', 'Sold'),
('Tucker', 'Cat', 4, 'Persian', 'Male', 'Available'),
('Harper', 'Bird', 3, 'Bulldog', 'Male', 'Sold'),
('Blue', 'Cat', 1, 'Bulldog', 'Male', 'Available'),
('Tucker', 'Dog', 8, 'Parrot', 'Female', 'Available'),
('Chloe', 'Rabbit', 2, 'Bulldog', 'Female', 'Under Treatment'),
('Nala', 'Dog', 9, 'Golden Retriever', 'Female', 'Available'),
('Ellie', 'Dog', 3, 'Siamese', 'Female', 'Available'),
('Oreo', 'Dog', 2, 'Parrot', 'Female', 'Sold'),
('Koda', 'Bird', 3, 'Holland Lop', 'Female', 'Sold'),
('Diesel', 'Rabbit', 9, 'Canary', 'Female', 'Available'),
('Cleo', 'Bird', 2, 'Parrot', 'Female', 'Under Treatment'),
('Sadie', 'Bird', 2, 'Canary', 'Male', 'Under Treatment'),
('Tucker', 'Bird', 9, 'Holland Lop', 'Male', 'Sold'),
('Ginger', 'Rabbit', 9, 'Siamese', 'Female', 'Available'),
('Scout', 'Dog', 8, 'Persian', 'Male', 'Under Treatment'),
('Moose', 'Bird', 5, 'Persian', 'Female', 'Sold'),
('Moose', 'Rabbit', 1, 'Siamese', 'Female', 'Available'),
('Dash', 'Cat', 8, 'Canary', 'Female', 'Available'),
('Diesel', 'Rabbit', 3, 'Poodle', 'Male', 'Available'),
('Hunter', 'Bird', 3, 'Labrador', 'Male', 'Under Treatment'),
('Hunter', 'Dog', 4, 'Holland Lop', 'Male', 'Under Treatment'),
('Koda', 'Dog', 2, 'Golden Retriever', 'Female', 'Available'),
('Dexter', 'Cat', 6, 'Labrador', 'Female', 'Sold'),
('Tucker', 'Bird', 9, 'Holland Lop', 'Male', 'Sold'),
('Cleo', 'Bird', 2, 'Beagle', 'Female', 'Sold'),
('Hazel', 'Cat', 9, 'Canary', 'Male', 'Available'),
('Finn', 'Rabbit', 8, 'Poodle', 'Male', 'Available'),
('Dash', 'Cat', 6, 'Canary', 'Female', 'Available'),
('Milo', 'Bird', 2, 'Beagle', 'Male', 'Available'),
('Scout', 'Cat', 5, 'Persian', 'Female', 'Under Treatment'),
('Hunter', 'Bird', 9, 'Labrador', 'Female', 'Available'),
('Sadie', 'Bird', 1, 'Labrador', 'Male', 'Under Treatment'),
('Finn', 'Rabbit', 10, 'Golden Retriever', 'Female', 'Sold'),
('Poppy', 'Dog', 7, 'Parrot', 'Male', 'Under Treatment'),
('Hunter', 'Cat', 6, 'Holland Lop', 'Female', 'Under Treatment'),
('Dash', 'Cat', 4, 'Canary', 'Male', 'Available'),
('Milo', 'Cat', 1, 'Canary', 'Male', 'Sold'),
('Hunter', 'Bird', 7, 'Golden Retriever', 'Female', 'Under Treatment'),
('Bailey', 'Bird', 3, 'Beagle', 'Female', 'Available'),
('Chloe', 'Dog', 4, 'Parrot', 'Male', 'Available'),
('Sadie', 'Dog', 2, 'Labrador', 'Female', 'Available'),
('Koda', 'Rabbit', 1, 'Beagle', 'Female', 'Sold'),
('Lily', 'Rabbit', 6, 'Holland Lop', 'Female', 'Sold'),
('Koda', 'Cat', 5, 'Siamese', 'Female', 'Available'),
('Dash', 'Cat', 1, 'Holland Lop', 'Male', 'Available'),
('Ruby', 'Bird', 7, 'Persian', 'Male', 'Sold'),
('Nala', 'Rabbit', 2, 'Siamese', 'Female', 'Available'),
('Nala', 'Dog', 1, 'Holland Lop', 'Female', 'Sold'),
('Milo', 'Cat', 1, 'Persian', 'Female', 'Available'),
('Milo', 'Dog', 5, 'Persian', 'Male', 'Under Treatment'),
('Hunter', 'Dog', 5, 'Labrador', 'Male', 'Sold'),
('Ellie', 'Dog', 6, 'Beagle', 'Male', 'Available'),
('Chloe', 'Dog', 10, 'Holland Lop', 'Female', 'Sold'),
('Hazel', 'Bird', 4, 'Persian', 'Male', 'Available'),
('Bailey', 'Rabbit', 7, 'Canary', 'Male', 'Sold'),
('Sadie', 'Rabbit', 9, 'Labrador', 'Female', 'Available'),
('Sadie', 'Cat', 2, 'Canary', 'Female', 'Under Treatment'),
('Harper', 'Dog', 9, 'Beagle', 'Male', 'Under Treatment'),
('Ellie', 'Bird', 8, 'Persian', 'Female', 'Available'),
('Koda', 'Cat', 9, 'Labrador', 'Male', 'Under Treatment'),
('Bailey', 'Rabbit', 1, 'Holland Lop', 'Female', 'Available'),
('Bailey', 'Cat', 8, 'Holland Lop', 'Female', 'Sold'),
('Diesel', 'Rabbit', 2, 'Persian', 'Male', 'Available'),
('Diesel', 'Rabbit', 2, 'Poodle', 'Male', 'Sold'),
('Ellie', 'Rabbit', 8, 'Canary', 'Male', 'Available'),
('Tucker', 'Dog', 6, 'Canary', 'Male', 'Available'),
('Chloe', 'Rabbit', 8, 'Golden Retriever', 'Male', 'Sold'),
('Ruby', 'Bird', 5, 'Persian', 'Female', 'Sold'),
('Tucker', 'Rabbit', 6, 'Poodle', 'Male', 'Sold'),
('Teddy', 'Rabbit', 4, 'Holland Lop', 'Female', 'Under Treatment'),
('Finn', 'Dog', 7, 'Poodle', 'Male', 'Under Treatment'),
('Cleo', 'Cat', 5, 'Bulldog', 'Female', 'Available'),
('Hunter', 'Rabbit', 7, 'Poodle', 'Male', 'Sold'),
('Teddy', 'Rabbit', 4, 'Poodle', 'Female', 'Under Treatment'),
('Cleo', 'Rabbit', 2, 'Persian', 'Male', 'Sold'),
('Marley', 'Dog', 6, 'Poodle', 'Female', 'Under Treatment'),
('Tucker', 'Rabbit', 1, 'Persian', 'Male', 'Under Treatment'),
('Hunter', 'Rabbit', 9, 'Labrador', 'Female', 'Available'),
('Dexter', 'Dog', 6, 'Beagle', 'Male', 'Available'),
('Poppy', 'Rabbit', 7, 'Persian', 'Male', 'Under Treatment'),
('Sadie', 'Rabbit', 2, 'Labrador', 'Male', 'Sold'),
('Chloe', 'Rabbit', 7, 'Persian', 'Female', 'Sold'),
('Dexter', 'Cat', 2, 'Holland Lop', 'Male', 'Sold'),
('Rosie', 'Rabbit', 5, 'Golden Retriever', 'Female', 'Under Treatment'),
('Marley', 'Rabbit', 7, 'Golden Retriever', 'Male', 'Under Treatment'),
('Teddy', 'Dog', 9, 'Beagle', 'Female', 'Under Treatment'),
('Rosie', 'Rabbit', 1, 'Siamese', 'Male', 'Available'),
('Stella', 'Bird', 1, 'Parrot', 'Female', 'Available'),
('Scout', 'Bird', 6, 'Labrador', 'Female', 'Sold'),
('Ginger', 'Cat', 2, 'Parrot', 'Female', 'Sold'),
('Scout', 'Cat', 2, 'Canary', 'Female', 'Available'),
('Moose', 'Cat', 2, 'Beagle', 'Female', 'Sold'),
('Dash', 'Cat', 2, 'Holland Lop', 'Male', 'Under Treatment'),
('Ruby', 'Bird', 1, 'Canary', 'Female', 'Under Treatment'),
('Stella', 'Bird', 3, 'Parrot', 'Female', 'Under Treatment'),
('Nala', 'Rabbit', 7, 'Poodle', 'Female', 'Sold'),
('Hazel', 'Rabbit', 8, 'Persian', 'Female', 'Under Treatment'),
('Teddy', 'Dog', 10, 'Persian', 'Male', 'Under Treatment'),
('Harper', 'Rabbit', 8, 'Siamese', 'Male', 'Available'),
('Marley', 'Cat', 6, 'Beagle', 'Female', 'Under Treatment'),
('Hazel', 'Dog', 5, 'Persian', 'Female', 'Sold'),
('Lily', 'Dog', 8, 'Beagle', 'Male', 'Under Treatment'),
('Moose', 'Bird', 7, 'Holland Lop', 'Male', 'Available'),
('Blue', 'Dog', 1, 'Siamese', 'Female', 'Sold'),
('Cleo', 'Cat', 4, 'Labrador', 'Male', 'Available'),
('Dash', 'Cat', 2, 'Persian', 'Male', 'Sold'),
('Ruby', 'Dog', 2, 'Bulldog', 'Male', 'Available'),
('Moose', 'Cat', 7, 'Persian', 'Male', 'Available'),
('Stella', 'Cat', 9, 'Persian', 'Male', 'Sold'),
('Scout', 'Bird', 1, 'Bulldog', 'Female', 'Under Treatment'),
('Stella', 'Rabbit', 9, 'Labrador', 'Male', 'Available'),
('Tucker', 'Rabbit', 8, 'Bulldog', 'Female', 'Sold'),
('Ruby', 'Dog', 9, 'Poodle', 'Male', 'Available'),
('Harper', 'Bird', 2, 'Bulldog', 'Male', 'Available'),
('Sadie', 'Dog', 10, 'Golden Retriever', 'Female', 'Under Treatment'),
('Nala', 'Bird', 1, 'Beagle', 'Female', 'Sold'),
('Dash', 'Rabbit', 8, 'Parrot', 'Male', 'Sold'),
('Chloe', 'Rabbit', 6, 'Labrador', 'Female', 'Under Treatment'),
('Tucker', 'Rabbit', 3, 'Beagle', 'Male', 'Sold'),
('Lily', 'Dog', 2, 'Labrador', 'Female', 'Sold'),
('Rosie', 'Dog', 5, 'Poodle', 'Male', 'Under Treatment'),
('Oreo', 'Cat', 10, 'Golden Retriever', 'Male', 'Under Treatment'),
('Poppy', 'Dog', 3, 'Siamese', 'Male', 'Sold'),
('Chloe', 'Bird', 8, 'Bulldog', 'Female', 'Under Treatment'),
('Nala', 'Dog', 1, 'Parrot', 'Male', 'Available'),
('Oreo', 'Cat', 7, 'Holland Lop', 'Male', 'Sold'),
('Ginger', 'Bird', 8, 'Siamese', 'Female', 'Available'),
('Diesel', 'Cat', 1, 'Siamese', 'Male', 'Available'),
('Teddy', 'Bird', 10, 'Beagle', 'Female', 'Available'),
('Bailey', 'Rabbit', 1, 'Holland Lop', 'Female', 'Under Treatment'),
('Tucker', 'Bird', 4, 'Beagle', 'Male', 'Sold'),
('Lily', 'Dog', 10, 'Persian', 'Female', 'Under Treatment'),
('Bailey', 'Rabbit', 9, 'Labrador', 'Male', 'Under Treatment'),
('Teddy', 'Rabbit', 4, 'Golden Retriever', 'Male', 'Under Treatment'),
('Rosie', 'Bird', 5, 'Beagle', 'Female', 'Available'),
('Koda', 'Cat', 8, 'Canary', 'Male', 'Available'),
('Finn', 'Bird', 9, 'Siamese', 'Female', 'Under Treatment'),
('Moose', 'Dog', 4, 'Beagle', 'Male', 'Under Treatment'),
('Ellie', 'Bird', 2, 'Golden Retriever', 'Female', 'Under Treatment'),
('Koda', 'Bird', 10, 'Beagle', 'Male', 'Under Treatment'),
('Pepper', 'Dog', 7, 'Bulldog', 'Female', 'Under Treatment'),
('Nala', 'Cat', 7, 'Poodle', 'Female', 'Available'),
('Harper', 'Dog', 2, 'Canary', 'Male', 'Available'),
('Poppy', 'Bird', 1, 'Beagle', 'Male', 'Available'),
('Chloe', 'Rabbit', 5, 'Canary', 'Female', 'Sold'),
('Bailey', 'Bird', 5, 'Golden Retriever', 'Female', 'Sold'),
('Ruby', 'Bird', 7, 'Labrador', 'Female', 'Under Treatment'),
('Lily', 'Cat', 6, 'Bulldog', 'Female', 'Sold'),
('Ruby', 'Bird', 1, 'Canary', 'Male', 'Sold'),
('Ellie', 'Cat', 4, 'Golden Retriever', 'Female', 'Under Treatment'),
('Lily', 'Cat', 9, 'Poodle', 'Female', 'Available'),
('Hazel', 'Dog', 4, 'Holland Lop', 'Male', 'Sold'),
('Chloe', 'Dog', 7, 'Beagle', 'Female', 'Under Treatment'),
('Harper', 'Bird', 7, 'Labrador', 'Male', 'Under Treatment'),
('Oreo', 'Bird', 5, 'Parrot', 'Female', 'Sold'),
('Bandit', 'Bird', 1, 'Poodle', 'Female', 'Sold'),
('Hunter', 'Rabbit', 3, 'Siamese', 'Male', 'Available'),
('Ginger', 'Cat', 8, 'Poodle', 'Female', 'Sold'),
('Pepper', 'Bird', 1, 'Labrador', 'Male', 'Sold'),
('Moose', 'Bird', 9, 'Siamese', 'Female', 'Under Treatment'),
('Ruby', 'Rabbit', 2, 'Golden Retriever', 'Female', 'Available'),
('Chloe', 'Dog', 10, 'Beagle', 'Female', 'Sold'),
('Ruby', 'Cat', 4, 'Poodle', 'Female', 'Sold'),
('Chloe', 'Cat', 4, 'Golden Retriever', 'Male', 'Available'),
('Nala', 'Cat', 1, 'Holland Lop', 'Female', 'Under Treatment'),
('Dash', 'Dog', 7, 'Persian', 'Female', 'Under Treatment'),
('Diesel', 'Cat', 10, 'Labrador', 'Male', 'Available'),
('Bandit', 'Bird', 10, 'Bulldog', 'Male', 'Available'),
('Scout', 'Rabbit', 8, 'Parrot', 'Female', 'Available'),
('Finn', 'Rabbit', 5, 'Parrot', 'Female', 'Under Treatment'),
('Chloe', 'Cat', 3, 'Siamese', 'Female', 'Under Treatment'),
('Tucker', 'Rabbit', 9, 'Parrot', 'Male', 'Under Treatment'),
('Ginger', 'Dog', 6, 'Parrot', 'Male', 'Available'),
('Teddy', 'Cat', 1, 'Golden Retriever', 'Female', 'Under Treatment'),
('Hunter', 'Bird', 4, 'Golden Retriever', 'Female', 'Under Treatment'),
('Ruby', 'Bird', 1, 'Siamese', 'Female', 'Available'),
('Finn', 'Dog', 5, 'Canary', 'Male', 'Sold'),
('Blue', 'Cat', 5, 'Parrot', 'Male', 'Sold'),
('Stella', 'Bird', 8, 'Beagle', 'Female', 'Available'),
('Ginger', 'Bird', 1, 'Poodle', 'Male', 'Under Treatment'),
('Chloe', 'Dog', 4, 'Persian', 'Male', 'Available'),
('Teddy', 'Cat', 6, 'Persian', 'Male', 'Available'),
('Oreo', 'Rabbit', 6, 'Siamese', 'Male', 'Sold'),
('Pepper', 'Rabbit', 6, 'Siamese', 'Male', 'Sold'),
('Ginger', 'Cat', 4, 'Golden Retriever', 'Female', 'Sold'),
('Ruby', 'Bird', 9, 'Holland Lop', 'Male', 'Sold'),
('Dexter', 'Cat', 6, 'Holland Lop', 'Male', 'Available'),
('Pepper', 'Rabbit', 4, 'Parrot', 'Female', 'Under Treatment'),
('Ginger', 'Cat', 2, 'Parrot', 'Male', 'Sold'),
('Pepper', 'Dog', 5, 'Persian', 'Male', 'Available'),
('Koda', 'Bird', 10, 'Golden Retriever', 'Female', 'Under Treatment'),
('Rosie', 'Dog', 3, 'Holland Lop', 'Male', 'Available'),
('Poppy', 'Cat', 6, 'Persian', 'Male', 'Under Treatment'),
('Hunter', 'Rabbit', 4, 'Golden Retriever', 'Female', 'Available'),
('Ellie', 'Rabbit', 8, 'Canary', 'Female', 'Under Treatment'),
('Sadie', 'Bird', 3, 'Parrot', 'Female', 'Under Treatment'),
('Dexter', 'Rabbit', 5, 'Golden Retriever', 'Male', 'Available'),
('Hazel', 'Cat', 8, 'Parrot', 'Male', 'Under Treatment'),
('Ruby', 'Cat', 8, 'Labrador', 'Female', 'Under Treatment'),
('Rosie', 'Cat', 6, 'Labrador', 'Female', 'Sold'),
('Diesel', 'Cat', 7, 'Persian', 'Female', 'Sold'),
('Koda', 'Dog', 7, 'Holland Lop', 'Female', 'Under Treatment'),
('Chloe', 'Cat', 6, 'Canary', 'Female', 'Sold'),
('Pepper', 'Cat', 3, 'Golden Retriever', 'Male', 'Available'),
('Lily', 'Cat', 1, 'Siamese', 'Male', 'Under Treatment'),
('Koda', 'Cat', 3, 'Siamese', 'Male', 'Available'),
('Ellie', 'Rabbit', 7, 'Parrot', 'Female', 'Sold'),
('Ruby', 'Bird', 10, 'Persian', 'Male', 'Under Treatment'),
('Ruby', 'Bird', 10, 'Canary', 'Female', 'Under Treatment'),
('Poppy', 'Cat', 7, 'Parrot', 'Female', 'Available'),
('Blue', 'Dog', 5, 'Canary', 'Male', 'Sold'),
('Nala', 'Dog', 5, 'Bulldog', 'Female', 'Available'),
('Ellie', 'Bird', 5, 'Siamese', 'Male', 'Available'),
('Scout', 'Bird', 9, 'Siamese', 'Female', 'Under Treatment'),
('Bandit', 'Rabbit', 2, 'Canary', 'Female', 'Under Treatment'),
('Ginger', 'Rabbit', 3, 'Holland Lop', 'Female', 'Sold'),
('Ellie', 'Cat', 9, 'Canary', 'Male', 'Under Treatment'),
('Tucker', 'Rabbit', 10, 'Persian', 'Male', 'Under Treatment'),
('Cleo', 'Dog', 2, 'Beagle', 'Female', 'Under Treatment'),
('Chloe', 'Rabbit', 1, 'Bulldog', 'Female', 'Available'),
('Bandit', 'Cat', 1, 'Labrador', 'Male', 'Sold'),
('Lily', 'Bird', 2, 'Beagle', 'Female', 'Sold'),
('Harper', 'Dog', 4, 'Poodle', 'Female', 'Available'),
('Hazel', 'Bird', 10, 'Poodle', 'Male', 'Under Treatment'),
('Hazel', 'Rabbit', 1, 'Labrador', 'Female', 'Sold'),
('Bailey', 'Cat', 2, 'Canary', 'Male', 'Under Treatment'),
('Tucker', 'Bird', 4, 'Siamese', 'Female', 'Available'),
('Pepper', 'Dog', 7, 'Beagle', 'Female', 'Under Treatment'),
('Koda', 'Rabbit', 1, 'Parrot', 'Male', 'Sold'),
('Ellie', 'Bird', 5, 'Golden Retriever', 'Male', 'Under Treatment'),
('Nala', 'Cat', 7, 'Siamese', 'Female', 'Sold'),
('Bandit', 'Rabbit', 1, 'Siamese', 'Male', 'Available'),
('Oreo', 'Dog', 4, 'Canary', 'Female', 'Under Treatment'),
('Hunter', 'Rabbit', 4, 'Parrot', 'Male', 'Sold'),
('Dexter', 'Cat', 6, 'Golden Retriever', 'Male', 'Under Treatment'),
('Moose', 'Dog', 6, 'Holland Lop', 'Male', 'Available'),
('Hazel', 'Dog', 10, 'Persian', 'Female', 'Sold'),
('Lily', 'Bird', 6, 'Persian', 'Male', 'Sold'),
('Cleo', 'Rabbit', 3, 'Persian', 'Male', 'Under Treatment'),
('Oreo', 'Bird', 4, 'Siamese', 'Female', 'Available'),
('Koda', 'Dog', 5, 'Bulldog', 'Male', 'Under Treatment'),
('Pepper', 'Cat', 2, 'Beagle', 'Male', 'Sold'),
('Dash', 'Cat', 10, 'Holland Lop', 'Female', 'Sold'),
('Nala', 'Dog', 7, 'Canary', 'Male', 'Sold'),
('Marley', 'Dog', 10, 'Persian', 'Female', 'Sold'),
('Bailey', 'Cat', 4, 'Holland Lop', 'Female', 'Under Treatment'),
('Scout', 'Rabbit', 10, 'Poodle', 'Female', 'Under Treatment'),
('Oreo', 'Rabbit', 10, 'Holland Lop', 'Male', 'Under Treatment'),
('Ginger', 'Dog', 4, 'Poodle', 'Female', 'Under Treatment'),
('Cleo', 'Bird', 9, 'Bulldog', 'Female', 'Available'),
('Dexter', 'Bird', 5, 'Labrador', 'Male', 'Under Treatment'),
('Blue', 'Cat', 3, 'Golden Retriever', 'Male', 'Available'),
('Teddy', 'Bird', 5, 'Labrador', 'Female', 'Under Treatment'),
('Scout', 'Rabbit', 5, 'Poodle', 'Female', 'Under Treatment'),
('Ellie', 'Cat', 7, 'Beagle', 'Female', 'Available'),
('Lily', 'Dog', 8, 'Canary', 'Female', 'Sold'),
('Bandit', 'Dog', 3, 'Canary', 'Male', 'Under Treatment'),
('Dexter', 'Cat', 2, 'Canary', 'Female', 'Sold'),
('Sadie', 'Dog', 1, 'Bulldog', 'Female', 'Sold'),
('Nala', 'Rabbit', 2, 'Beagle', 'Male', 'Available'),
('Cleo', 'Dog', 9, 'Holland Lop', 'Male', 'Under Treatment'),
('Moose', 'Rabbit', 3, 'Holland Lop', 'Female', 'Sold'),
('Tucker', 'Cat', 2, 'Golden Retriever', 'Male', 'Under Treatment'),
('Nala', 'Dog', 9, 'Canary', 'Male', 'Sold'),
('Koda', 'Cat', 9, 'Siamese', 'Male', 'Sold'),
('Nala', 'Cat', 5, 'Golden Retriever', 'Female', 'Sold'),
('Pepper', 'Bird', 10, 'Golden Retriever', 'Male', 'Available'),
('Cleo', 'Rabbit', 2, 'Siamese', 'Female', 'Sold'),
('Marley', 'Rabbit', 2, 'Labrador', 'Female', 'Available'),
('Sadie', 'Dog', 4, 'Bulldog', 'Female', 'Sold'),
('Koda', 'Bird', 9, 'Parrot', 'Male', 'Available'),
('Lily', 'Bird', 7, 'Canary', 'Female', 'Under Treatment'),
('Nala', 'Bird', 9, 'Labrador', 'Female', 'Sold'),
('Pepper', 'Rabbit', 10, 'Bulldog', 'Female', 'Available'),
('Teddy', 'Rabbit', 6, 'Bulldog', 'Male', 'Under Treatment'),
('Marley', 'Bird', 2, 'Persian', 'Female', 'Sold'),
('Marley', 'Cat', 8, 'Holland Lop', 'Male', 'Sold'),
('Chloe', 'Bird', 5, 'Poodle', 'Female', 'Available'),
('Scout', 'Rabbit', 8, 'Poodle', 'Male', 'Under Treatment'),
('Scout', 'Cat', 3, 'Poodle', 'Female', 'Available'),
('Sadie', 'Bird', 9, 'Beagle', 'Female', 'Under Treatment'),
('Teddy', 'Cat', 2, 'Golden Retriever', 'Male', 'Sold'),
('Poppy', 'Dog', 6, 'Labrador', 'Male', 'Available'),
('Finn', 'Dog', 3, 'Holland Lop', 'Male', 'Available'),
('Pepper', 'Bird', 2, 'Poodle', 'Male', 'Available'),
('Scout', 'Bird', 10, 'Siamese', 'Male', 'Available'),
('Pepper', 'Rabbit', 5, 'Holland Lop', 'Male', 'Sold'),
('Milo', 'Dog', 7, 'Holland Lop', 'Male', 'Sold'),
('Poppy', 'Dog', 1, 'Labrador', 'Female', 'Available'),
('Harper', 'Cat', 5, 'Canary', 'Female', 'Available'),
('Cleo', 'Cat', 4, 'Poodle', 'Female', 'Under Treatment'),
('Scout', 'Cat', 2, 'Holland Lop', 'Male', 'Available'),
('Nala', 'Rabbit', 1, 'Golden Retriever', 'Female', 'Sold'),
('Rosie', 'Dog', 1, 'Golden Retriever', 'Male', 'Available'),
('Stella', 'Cat', 1, 'Poodle', 'Male', 'Available'),
('Chloe', 'Bird', 3, 'Canary', 'Female', 'Available'),
('Hazel', 'Dog', 3, 'Holland Lop', 'Female', 'Available'),
('Ruby', 'Rabbit', 2, 'Siamese', 'Male', 'Under Treatment'),
('Bailey', 'Cat', 6, 'Beagle', 'Male', 'Under Treatment'),
('Finn', 'Dog', 8, 'Bulldog', 'Male', 'Under Treatment'),
('Rosie', 'Bird', 5, 'Labrador', 'Female', 'Available'),
('Finn', 'Cat', 6, 'Beagle', 'Female', 'Available'),
('Hazel', 'Cat', 8, 'Bulldog', 'Female', 'Under Treatment'),
('Milo', 'Cat', 4, 'Persian', 'Male', 'Sold'),
('Diesel', 'Cat', 3, 'Beagle', 'Female', 'Under Treatment'),
('Moose', 'Dog', 8, 'Golden Retriever', 'Female', 'Under Treatment'),
('Hunter', 'Dog', 3, 'Golden Retriever', 'Male', 'Sold'),
('Diesel', 'Dog', 8, 'Labrador', 'Male', 'Available'),
('Poppy', 'Rabbit', 10, 'Beagle', 'Female', 'Sold'),
('Nala', 'Cat', 6, 'Persian', 'Male', 'Available'),
('Hazel', 'Bird', 9, 'Persian', 'Female', 'Available'),
('Nala', 'Cat', 4, 'Poodle', 'Male', 'Available'),
('Moose', 'Bird', 2, 'Persian', 'Male', 'Under Treatment'),
('Ellie', 'Dog', 7, 'Canary', 'Male', 'Under Treatment'),
('Ruby', 'Cat', 8, 'Canary', 'Female', 'Sold'),
('Ruby', 'Dog', 8, 'Siamese', 'Female', 'Available'),
('Poppy', 'Dog', 4, 'Beagle', 'Male', 'Available'),
('Diesel', 'Rabbit', 3, 'Golden Retriever', 'Male', 'Under Treatment'),
('Koda', 'Cat', 5, 'Siamese', 'Male', 'Sold'),
('Ellie', 'Dog', 10, 'Parrot', 'Female', 'Sold'),
('Tucker', 'Bird', 4, 'Siamese', 'Female', 'Sold'),
('Cleo', 'Bird', 7, 'Holland Lop', 'Male', 'Sold'),
('Stella', 'Rabbit', 10, 'Golden Retriever', 'Female', 'Under Treatment'),
('Tucker', 'Cat', 1, 'Holland Lop', 'Male', 'Under Treatment'),
('Finn', 'Dog', 10, 'Golden Retriever', 'Male', 'Under Treatment'),
('Nala', 'Dog', 3, 'Canary', 'Male', 'Under Treatment'),
('Teddy', 'Dog', 8, 'Labrador', 'Female', 'Sold'),
('Hunter', 'Bird', 7, 'Canary', 'Female', 'Sold'),
('Diesel', 'Bird', 3, 'Persian', 'Female', 'Under Treatment'),
('Cleo', 'Bird', 3, 'Labrador', 'Male', 'Available'),
('Cleo', 'Cat', 4, 'Siamese', 'Male', 'Available'),
('Hazel', 'Dog', 5, 'Beagle', 'Male', 'Under Treatment'),
('Pepper', 'Rabbit', 8, 'Poodle', 'Male', 'Under Treatment'),
('Harper', 'Cat', 5, 'Canary', 'Female', 'Available'),
('Hunter', 'Cat', 6, 'Canary', 'Male', 'Sold'),
('Ginger', 'Dog', 3, 'Bulldog', 'Male', 'Available'),
('Tucker', 'Rabbit', 1, 'Parrot', 'Female', 'Under Treatment'),
('Harper', 'Bird', 8, 'Beagle', 'Female', 'Available'),
('Diesel', 'Bird', 2, 'Beagle', 'Male', 'Under Treatment'),
('Tucker', 'Bird', 5, 'Golden Retriever', 'Female', 'Available'),
('Ellie', 'Cat', 3, 'Labrador', 'Male', 'Available'),
('Diesel', 'Cat', 6, 'Beagle', 'Female', 'Available'),
('Nala', 'Cat', 8, 'Holland Lop', 'Male', 'Available'),
('Finn', 'Dog', 3, 'Beagle', 'Male', 'Under Treatment'),
('Ginger', 'Rabbit', 3, 'Labrador', 'Male', 'Available'),
('Hunter', 'Rabbit', 6, 'Siamese', 'Female', 'Under Treatment'),
('Moose', 'Rabbit', 7, 'Persian', 'Female', 'Sold'),
('Moose', 'Cat', 7, 'Parrot', 'Male', 'Available'),
('Ruby', 'Cat', 7, 'Siamese', 'Male', 'Available'),
('Tucker', 'Dog', 8, 'Canary', 'Male', 'Under Treatment'),
('Finn', 'Rabbit', 5, 'Parrot', 'Male', 'Sold'),
('Rosie', 'Bird', 3, 'Bulldog', 'Male', 'Available'),
('Diesel', 'Bird', 8, 'Canary', 'Male', 'Under Treatment'),
('Koda', 'Cat', 4, 'Poodle', 'Female', 'Under Treatment'),
('Poppy', 'Dog', 5, 'Canary', 'Male', 'Under Treatment'),
('Nala', 'Rabbit', 10, 'Holland Lop', 'Female', 'Under Treatment'),
('Tucker', 'Rabbit', 5, 'Persian', 'Male', 'Available'),
('Marley', 'Cat', 5, 'Holland Lop', 'Female', 'Available'),
('Diesel', 'Rabbit', 7, 'Bulldog', 'Male', 'Sold'),
('Teddy', 'Dog', 3, 'Beagle', 'Female', 'Available'),
('Moose', 'Cat', 6, 'Canary', 'Male', 'Available'),
('Cleo', 'Cat', 1, 'Bulldog', 'Male', 'Under Treatment'),
('Rosie', 'Cat', 9, 'Beagle', 'Female', 'Available'),
('Teddy', 'Dog', 5, 'Siamese', 'Female', 'Under Treatment'),
('Poppy', 'Bird', 8, 'Parrot', 'Male', 'Under Treatment'),
('Finn', 'Cat', 7, 'Canary', 'Male', 'Under Treatment'),
('Teddy', 'Dog', 8, 'Golden Retriever', 'Female', 'Under Treatment'),
('Blue', 'Bird', 1, 'Parrot', 'Female', 'Sold'),
('Chloe', 'Dog', 3, 'Bulldog', 'Female', 'Sold'),
('Finn', 'Rabbit', 2, 'Canary', 'Male', 'Available'),
('Scout', 'Cat', 10, 'Beagle', 'Male', 'Available'),
('Hazel', 'Cat', 10, 'Golden Retriever', 'Female', 'Under Treatment'),
('Marley', 'Rabbit', 2, 'Parrot', 'Male', 'Sold'),
('Koda', 'Rabbit', 6, 'Golden Retriever', 'Male', 'Sold'),
('Chloe', 'Cat', 3, 'Holland Lop', 'Male', 'Under Treatment'),
('Moose', 'Bird', 9, 'Holland Lop', 'Male', 'Available'),
('Poppy', 'Cat', 5, 'Persian', 'Male', 'Available'),
('Hunter', 'Cat', 8, 'Holland Lop', 'Female', 'Under Treatment'),
('Sadie', 'Bird', 7, 'Canary', 'Female', 'Under Treatment'),
('Diesel', 'Bird', 4, 'Persian', 'Female', 'Sold'),
('Finn', 'Cat', 7, 'Persian', 'Male', 'Under Treatment'),
('Finn', 'Bird', 4, 'Parrot', 'Female', 'Sold'),
('Rosie', 'Cat', 6, 'Canary', 'Female', 'Sold'),
('Dash', 'Dog', 3, 'Beagle', 'Female', 'Sold'),
('Bailey', 'Dog', 6, 'Golden Retriever', 'Female', 'Available'),
('Diesel', 'Bird', 2, 'Golden Retriever', 'Male', 'Available'),
('Blue', 'Cat', 10, 'Labrador', 'Male', 'Available'),
('Scout', 'Dog', 5, 'Golden Retriever', 'Female', 'Under Treatment'),
('Koda', 'Rabbit', 9, 'Golden Retriever', 'Male', 'Sold'),
('Ginger', 'Dog', 4, 'Labrador', 'Female', 'Under Treatment'),
('Cleo', 'Rabbit', 6, 'Bulldog', 'Female', 'Under Treatment'),
('Dexter', 'Rabbit', 5, 'Siamese', 'Female', 'Under Treatment'),
('Ellie', 'Bird', 7, 'Labrador', 'Female', 'Under Treatment'),
('Stella', 'Bird', 3, 'Holland Lop', 'Female', 'Under Treatment'),
('Chloe', 'Rabbit', 8, 'Parrot', 'Female', 'Under Treatment'),
('Rosie', 'Bird', 6, 'Siamese', 'Male', 'Under Treatment'),
('Chloe', 'Bird', 5, 'Holland Lop', 'Female', 'Under Treatment'),
('Dexter', 'Bird', 10, 'Holland Lop', 'Female', 'Available'),
('Milo', 'Rabbit', 5, 'Poodle', 'Female', 'Under Treatment'),
('Marley', 'Cat', 3, 'Golden Retriever', 'Male', 'Under Treatment'),
('Milo', 'Cat', 1, 'Bulldog', 'Male', 'Under Treatment'),
('Nala', 'Cat', 9, 'Bulldog', 'Female', 'Sold'),
('Ginger', 'Dog', 10, 'Holland Lop', 'Male', 'Available'),
('Bandit', 'Rabbit', 4, 'Poodle', 'Female', 'Available'),
('Dash', 'Dog', 9, 'Bulldog', 'Female', 'Available'),
('Dexter', 'Rabbit', 6, 'Golden Retriever', 'Female', 'Sold'),
('Pepper', 'Bird', 10, 'Persian', 'Male', 'Available'),
('Hunter', 'Rabbit', 1, 'Persian', 'Male', 'Sold'),
('Pepper', 'Cat', 7, 'Labrador', 'Female', 'Sold'),
('Nala', 'Bird', 7, 'Holland Lop', 'Female', 'Available'),
('Ginger', 'Bird', 6, 'Persian', 'Male', 'Available'),
('Bandit', 'Cat', 7, 'Labrador', 'Male', 'Sold'),
('Cleo', 'Rabbit', 6, 'Holland Lop', 'Male', 'Sold'),
('Milo', 'Dog', 3, 'Siamese', 'Male', 'Available'),
('Stella', 'Cat', 1, 'Siamese', 'Female', 'Sold'),
('Hazel', 'Rabbit', 8, 'Poodle', 'Male', 'Sold'),
('Lily', 'Bird', 8, 'Parrot', 'Female', 'Available'),
('Hazel', 'Rabbit', 1, 'Persian', 'Male', 'Under Treatment'),
('Bandit', 'Bird', 7, 'Golden Retriever', 'Male', 'Available'),
('Hunter', 'Bird', 3, 'Golden Retriever', 'Male', 'Under Treatment'),
('Chloe', 'Rabbit', 7, 'Holland Lop', 'Female', 'Under Treatment'),
('Nala', 'Bird', 4, 'Bulldog', 'Male', 'Available'),
('Lily', 'Cat', 1, 'Beagle', 'Female', 'Available'),
('Poppy', 'Dog', 5, 'Labrador', 'Female', 'Sold'),
('Hazel', 'Bird', 9, 'Golden Retriever', 'Female', 'Sold'),
('Moose', 'Bird', 10, 'Canary', 'Male', 'Under Treatment'),
('Ruby', 'Rabbit', 3, 'Bulldog', 'Female', 'Under Treatment'),
('Chloe', 'Bird', 10, 'Labrador', 'Male', 'Sold'),
('Tucker', 'Bird', 8, 'Labrador', 'Male', 'Available'),
('Stella', 'Cat', 3, 'Beagle', 'Female', 'Available'),
('Lily', 'Rabbit', 6, 'Poodle', 'Male', 'Available'),
('Bailey', 'Cat', 2, 'Canary', 'Female', 'Under Treatment'),
('Marley', 'Bird', 4, 'Persian', 'Male', 'Available'),
('Harper', 'Rabbit', 9, 'Bulldog', 'Female', 'Under Treatment'),
('Hazel', 'Rabbit', 6, 'Holland Lop', 'Male', 'Available'),
('Sadie', 'Rabbit', 6, 'Siamese', 'Male', 'Under Treatment'),
('Nala', 'Bird', 6, 'Canary', 'Female', 'Sold'),
('Rosie', 'Dog', 7, 'Parrot', 'Male', 'Under Treatment'),
('Hazel', 'Bird', 4, 'Canary', 'Male', 'Available'),
('Sadie', 'Bird', 6, 'Parrot', 'Male', 'Available'),
('Harper', 'Dog', 9, 'Labrador', 'Female', 'Available'),
('Rosie', 'Dog', 7, 'Labrador', 'Male', 'Sold'),
('Moose', 'Dog', 7, 'Canary', 'Female', 'Under Treatment'),
('Ginger', 'Rabbit', 8, 'Bulldog', 'Male', 'Under Treatment'),
('Chloe', 'Bird', 8, 'Siamese', 'Female', 'Available'),
('Chloe', 'Cat', 4, 'Holland Lop', 'Female', 'Available'),
('Nala', 'Dog', 9, 'Parrot', 'Female', 'Available'),
('Chloe', 'Bird', 6, 'Beagle', 'Female', 'Sold'),
('Hazel', 'Rabbit', 6, 'Bulldog', 'Female', 'Sold'),
('Dash', 'Cat', 10, 'Golden Retriever', 'Female', 'Sold'),
('Chloe', 'Rabbit', 8, 'Canary', 'Male', 'Sold'),
('Marley', 'Bird', 6, 'Siamese', 'Male', 'Under Treatment'),
('Koda', 'Cat', 6, 'Golden Retriever', 'Female', 'Under Treatment'),
('Pepper', 'Rabbit', 7, 'Siamese', 'Male', 'Available'),
('Poppy', 'Bird', 1, 'Beagle', 'Female', 'Under Treatment'),
('Ellie', 'Bird', 5, 'Labrador', 'Male', 'Under Treatment'),
('Oreo', 'Dog', 8, 'Poodle', 'Female', 'Under Treatment'),
('Chloe', 'Cat', 7, 'Golden Retriever', 'Male', 'Available'),
('Teddy', 'Dog', 5, 'Bulldog', 'Female', 'Available'),
('Sadie', 'Dog', 1, 'Siamese', 'Male', 'Sold'),
('Tucker', 'Rabbit', 7, 'Labrador', 'Male', 'Available'),
('Lily', 'Rabbit', 8, 'Poodle', 'Male', 'Sold'),
('Dexter', 'Bird', 4, 'Labrador', 'Female', 'Under Treatment'),
('Lily', 'Cat', 1, 'Poodle', 'Female', 'Available'),
('Ginger', 'Bird', 6, 'Canary', 'Male', 'Under Treatment'),
('Hazel', 'Bird', 8, 'Golden Retriever', 'Male', 'Sold'),
('Hazel', 'Rabbit', 3, 'Canary', 'Male', 'Sold'),
('Poppy', 'Cat', 10, 'Labrador', 'Female', 'Under Treatment'),
('Harper', 'Dog', 10, 'Golden Retriever', 'Female', 'Available'),
('Pepper', 'Bird', 4, 'Persian', 'Female', 'Available'),
('Bandit', 'Dog', 7, 'Parrot', 'Male', 'Under Treatment'),
('Scout', 'Bird', 4, 'Holland Lop', 'Female', 'Available'),
('Koda', 'Dog', 7, 'Golden Retriever', 'Female', 'Under Treatment'),
('Tucker', 'Bird', 5, 'Golden Retriever', 'Female', 'Available'),
('Cleo', 'Dog', 3, 'Golden Retriever', 'Male', 'Available'),
('Moose', 'Cat', 1, 'Persian', 'Male', 'Sold'),
('Ruby', 'Cat', 8, 'Labrador', 'Male', 'Under Treatment'),
('Dash', 'Cat', 7, 'Canary', 'Male', 'Under Treatment'),
('Rosie', 'Cat', 6, 'Bulldog', 'Male', 'Sold'),
('Finn', 'Bird', 5, 'Golden Retriever', 'Male', 'Available'),
('Stella', 'Bird', 3, 'Canary', 'Female', 'Sold'),
('Stella', 'Dog', 1, 'Golden Retriever', 'Male', 'Sold'),
('Stella', 'Bird', 2, 'Beagle', 'Male', 'Sold'),
('Ellie', 'Bird', 2, 'Bulldog', 'Male', 'Sold'),
('Koda', 'Cat', 5, 'Persian', 'Female', 'Available'),
('Moose', 'Bird', 4, 'Labrador', 'Male', 'Sold'),
('Finn', 'Rabbit', 6, 'Bulldog', 'Male', 'Available'),
('Scout', 'Bird', 8, 'Golden Retriever', 'Female', 'Under Treatment'),
('Rosie', 'Bird', 1, 'Bulldog', 'Male', 'Under Treatment'),
('Bailey', 'Dog', 5, 'Canary', 'Male', 'Sold'),
('Ellie', 'Cat', 2, 'Persian', 'Male', 'Sold'),
('Bailey', 'Rabbit', 3, 'Golden Retriever', 'Male', 'Under Treatment'),
('Moose', 'Cat', 5, 'Parrot', 'Male', 'Available'),
('Sadie', 'Rabbit', 10, 'Canary', 'Female', 'Under Treatment'),
('Pepper', 'Bird', 7, 'Parrot', 'Female', 'Sold'),
('Poppy', 'Bird', 2, 'Siamese', 'Female', 'Sold'),
('Dash', 'Cat', 7, 'Poodle', 'Female', 'Available'),
('Ginger', 'Rabbit', 6, 'Poodle', 'Male', 'Available'),
('Chloe', 'Cat', 2, 'Bulldog', 'Male', 'Available'),
('Hunter', 'Dog', 6, 'Holland Lop', 'Male', 'Under Treatment'),
('Cleo', 'Rabbit', 6, 'Golden Retriever', 'Female', 'Available'),
('Pepper', 'Bird', 8, 'Persian', 'Male', 'Available'),
('Hazel', 'Cat', 2, 'Parrot', 'Female', 'Under Treatment'),
('Chloe', 'Bird', 1, 'Canary', 'Female', 'Sold'),
('Blue', 'Cat', 1, 'Canary', 'Male', 'Available'),
('Moose', 'Rabbit', 2, 'Golden Retriever', 'Female', 'Available'),
('Finn', 'Cat', 1, 'Golden Retriever', 'Male', 'Under Treatment'),
('Scout', 'Cat', 7, 'Labrador', 'Female', 'Sold'),
('Marley', 'Dog', 7, 'Poodle', 'Male', 'Sold'),
('Poppy', 'Cat', 6, 'Persian', 'Female', 'Under Treatment'),
('Chloe', 'Dog', 6, 'Parrot', 'Female', 'Sold'),
('Oreo', 'Dog', 4, 'Persian', 'Male', 'Under Treatment'),
('Sadie', 'Dog', 8, 'Siamese', 'Female', 'Sold'),
('Milo', 'Rabbit', 9, 'Golden Retriever', 'Male', 'Available'),
('Scout', 'Dog', 6, 'Beagle', 'Female', 'Sold'),
('Dash', 'Rabbit', 1, 'Siamese', 'Female', 'Under Treatment'),
('Koda', 'Cat', 5, 'Beagle', 'Male', 'Available'),
('Sadie', 'Rabbit', 6, 'Poodle', 'Female', 'Available'),
('Pepper', 'Rabbit', 6, 'Beagle', 'Female', 'Sold'),
('Poppy', 'Dog', 4, 'Siamese', 'Female', 'Available'),
('Ellie', 'Cat', 10, 'Parrot', 'Male', 'Sold'),
('Scout', 'Dog', 8, 'Persian', 'Female', 'Sold'),
('Rosie', 'Bird', 1, 'Parrot', 'Female', 'Under Treatment'),
('Koda', 'Cat', 1, 'Poodle', 'Female', 'Under Treatment'),
('Scout', 'Dog', 1, 'Beagle', 'Female', 'Under Treatment'),
('Koda', 'Cat', 6, 'Poodle', 'Female', 'Sold'),
('Pepper', 'Cat', 4, 'Persian', 'Female', 'Sold'),
('Ellie', 'Dog', 2, 'Poodle', 'Female', 'Under Treatment'),
('Cleo', 'Rabbit', 2, 'Labrador', 'Female', 'Under Treatment'),
('Sadie', 'Bird', 9, 'Golden Retriever', 'Male', 'Under Treatment'),
('Tucker', 'Dog', 4, 'Beagle', 'Female', 'Under Treatment'),
('Bandit', 'Cat', 1, 'Beagle', 'Male', 'Under Treatment'),
('Finn', 'Rabbit', 8, 'Parrot', 'Female', 'Available'),
('Ruby', 'Bird', 5, 'Labrador', 'Male', 'Sold'),
('Bandit', 'Bird', 4, 'Bulldog', 'Female', 'Available'),
('Bailey', 'Rabbit', 5, 'Poodle', 'Female', 'Under Treatment'),
('Stella', 'Dog', 8, 'Bulldog', 'Female', 'Under Treatment'),
('Bandit', 'Cat', 2, 'Golden Retriever', 'Male', 'Sold'),
('Hunter', 'Dog', 4, 'Labrador', 'Male', 'Available'),
('Chloe', 'Rabbit', 4, 'Parrot', 'Male', 'Sold'),
('Cleo', 'Cat', 5, 'Canary', 'Male', 'Under Treatment'),
('Cleo', 'Rabbit', 9, 'Golden Retriever', 'Male', 'Available'),
('Pepper', 'Cat', 3, 'Holland Lop', 'Female', 'Available'),
('Tucker', 'Bird', 6, 'Canary', 'Male', 'Available'),
('Tucker', 'Dog', 4, 'Beagle', 'Female', 'Under Treatment'),
('Nala', 'Rabbit', 6, 'Holland Lop', 'Female', 'Under Treatment'),
('Moose', 'Cat', 5, 'Persian', 'Female', 'Available'),
('Blue', 'Dog', 4, 'Persian', 'Male', 'Sold'),
('Ellie', 'Bird', 10, 'Golden Retriever', 'Male', 'Sold'),
('Scout', 'Rabbit', 9, 'Poodle', 'Female', 'Sold'),
('Scout', 'Cat', 2, 'Golden Retriever', 'Female', 'Available'),
('Bandit', 'Bird', 4, 'Beagle', 'Female', 'Under Treatment'),
('Milo', 'Cat', 5, 'Parrot', 'Female', 'Under Treatment'),
('Diesel', 'Rabbit', 5, 'Poodle', 'Female', 'Available'),
('Ruby', 'Rabbit', 5, 'Golden Retriever', 'Male', 'Sold'),
('Scout', 'Dog', 2, 'Canary', 'Female', 'Available'),
('Stella', 'Bird', 4, 'Canary', 'Female', 'Available'),
('Blue', 'Cat', 7, 'Bulldog', 'Female', 'Sold'),
('Koda', 'Dog', 4, 'Persian', 'Male', 'Under Treatment'),
('Scout', 'Dog', 1, 'Holland Lop', 'Male', 'Available'),
('Koda', 'Dog', 10, 'Siamese', 'Female', 'Available'),
('Ginger', 'Bird', 4, 'Golden Retriever', 'Male', 'Sold'),
('Marley', 'Cat', 6, 'Poodle', 'Female', 'Available'),
('Tucker', 'Dog', 9, 'Parrot', 'Female', 'Sold'),
('Diesel', 'Dog', 5, 'Parrot', 'Female', 'Available'),
('Poppy', 'Dog', 8, 'Labrador', 'Male', 'Sold'),
('Harper', 'Dog', 8, 'Golden Retriever', 'Male', 'Sold'),
('Scout', 'Bird', 1, 'Holland Lop', 'Male', 'Available'),
('Ellie', 'Cat', 9, 'Poodle', 'Female', 'Sold'),
('Cleo', 'Bird', 1, 'Poodle', 'Male', 'Under Treatment'),
('Stella', 'Cat', 2, 'Beagle', 'Male', 'Sold'),
('Hazel', 'Rabbit', 1, 'Siamese', 'Male', 'Available'),
('Ginger', 'Rabbit', 4, 'Bulldog', 'Female', 'Available'),
('Oreo', 'Cat', 7, 'Beagle', 'Female', 'Sold'),
('Tucker', 'Bird', 7, 'Golden Retriever', 'Male', 'Sold'),
('Blue', 'Bird', 1, 'Poodle', 'Female', 'Available'),
('Hunter', 'Bird', 3, 'Siamese', 'Female', 'Available'),
('Cleo', 'Rabbit', 1, 'Persian', 'Male', 'Available'),
('Harper', 'Bird', 8, 'Golden Retriever', 'Female', 'Available'),
('Diesel', 'Bird', 2, 'Siamese', 'Female', 'Sold'),
('Finn', 'Bird', 2, 'Golden Retriever', 'Female', 'Sold'),
('Bandit', 'Cat', 10, 'Siamese', 'Female', 'Available'),
('Dash', 'Cat', 4, 'Beagle', 'Female', 'Available'),
('Finn', 'Cat', 1, 'Siamese', 'Male', 'Under Treatment'),
('Sadie', 'Dog', 10, 'Bulldog', 'Male', 'Under Treatment'),
('Rosie', 'Bird', 3, 'Canary', 'Female', 'Sold'),
('Chloe', 'Dog', 7, 'Siamese', 'Male', 'Sold'),
('Ruby', 'Cat', 1, 'Canary', 'Female', 'Available'),
('Oreo', 'Bird', 1, 'Persian', 'Male', 'Under Treatment'),
('Stella', 'Dog', 2, 'Holland Lop', 'Female', 'Sold'),
('Moose', 'Rabbit', 6, 'Parrot', 'Female', 'Available'),
('Oreo', 'Cat', 3, 'Persian', 'Male', 'Available'),
('Teddy', 'Rabbit', 3, 'Canary', 'Female', 'Sold'),
('Bailey', 'Cat', 3, 'Holland Lop', 'Female', 'Available'),
('Rosie', 'Rabbit', 7, 'Bulldog', 'Female', 'Sold'),
('Rosie', 'Bird', 9, 'Golden Retriever', 'Male', 'Under Treatment'),
('Scout', 'Bird', 10, 'Poodle', 'Male', 'Available'),
('Milo', 'Cat', 10, 'Labrador', 'Female', 'Under Treatment'),
('Scout', 'Dog', 1, 'Canary', 'Male', 'Under Treatment'),
('Blue', 'Rabbit', 4, 'Poodle', 'Male', 'Under Treatment'),
('Stella', 'Rabbit', 10, 'Bulldog', 'Male', 'Under Treatment'),
('Bailey', 'Bird', 2, 'Canary', 'Male', 'Available'),
('Bailey', 'Cat', 4, 'Golden Retriever', 'Female', 'Sold'),
('Moose', 'Bird', 1, 'Siamese', 'Female', 'Sold'),
('Hunter', 'Bird', 7, 'Labrador', 'Female', 'Available'),
('Diesel', 'Rabbit', 10, 'Holland Lop', 'Female', 'Under Treatment'),
('Marley', 'Bird', 10, 'Labrador', 'Female', 'Sold'),
('Lily', 'Dog', 8, 'Siamese', 'Male', 'Available'),
('Scout', 'Cat', 5, 'Canary', 'Female', 'Under Treatment'),
('Blue', 'Cat', 7, 'Labrador', 'Female', 'Sold'),
('Lily', 'Bird', 6, 'Bulldog', 'Male', 'Sold'),
('Hunter', 'Cat', 2, 'Beagle', 'Male', 'Under Treatment'),
('Blue', 'Cat', 3, 'Parrot', 'Male', 'Sold'),
('Hunter', 'Rabbit', 1, 'Parrot', 'Male', 'Under Treatment'),
('Blue', 'Rabbit', 9, 'Persian', 'Female', 'Available'),
('Bailey', 'Bird', 2, 'Persian', 'Male', 'Available'),
('Chloe', 'Cat', 10, 'Poodle', 'Male', 'Sold'),
('Dash', 'Rabbit', 4, 'Golden Retriever', 'Male', 'Available'),
('Milo', 'Rabbit', 4, 'Golden Retriever', 'Female', 'Under Treatment'),
('Pepper', 'Bird', 10, 'Bulldog', 'Male', 'Sold'),
('Lily', 'Bird', 7, 'Persian', 'Male', 'Available'),
('Moose', 'Dog', 8, 'Bulldog', 'Female', 'Available'),
('Koda', 'Dog', 8, 'Bulldog', 'Male', 'Under Treatment'),
('Milo', 'Rabbit', 9, 'Siamese', 'Female', 'Available'),
('Hazel', 'Rabbit', 3, 'Canary', 'Female', 'Sold'),
('Teddy', 'Cat', 10, 'Labrador', 'Male', 'Under Treatment'),
('Dash', 'Bird', 1, 'Siamese', 'Male', 'Sold'),
('Scout', 'Rabbit', 7, 'Bulldog', 'Female', 'Under Treatment'),
('Sadie', 'Rabbit', 1, 'Siamese', 'Female', 'Under Treatment'),
('Oreo', 'Cat', 10, 'Labrador', 'Male', 'Sold'),
('Dash', 'Rabbit', 1, 'Bulldog', 'Female', 'Under Treatment'),
('Marley', 'Cat', 5, 'Parrot', 'Female', 'Available'),
('Tucker', 'Rabbit', 7, 'Parrot', 'Male', 'Under Treatment'),
('Moose', 'Dog', 6, 'Bulldog', 'Male', 'Available'),
('Ginger', 'Cat', 5, 'Labrador', 'Male', 'Under Treatment'),
('Marley', 'Bird', 9, 'Parrot', 'Female', 'Available'),
('Ruby', 'Cat', 8, 'Siamese', 'Male', 'Under Treatment'),
('Ruby', 'Cat', 10, 'Poodle', 'Male', 'Available'),
('Rosie', 'Rabbit', 10, 'Poodle', 'Female', 'Under Treatment'),
('Milo', 'Rabbit', 7, 'Parrot', 'Male', 'Under Treatment'),
('Diesel', 'Dog', 7, 'Bulldog', 'Female', 'Under Treatment'),
('Sadie', 'Cat', 3, 'Poodle', 'Male', 'Available'),
('Stella', 'Rabbit', 6, 'Bulldog', 'Female', 'Sold'),
('Tucker', 'Cat', 2, 'Canary', 'Female', 'Under Treatment'),
('Hazel', 'Rabbit', 1, 'Parrot', 'Male', 'Available'),
('Ellie', 'Rabbit', 4, 'Beagle', 'Female', 'Under Treatment'),
('Rosie', 'Bird', 10, 'Poodle', 'Male', 'Sold'),
('Dexter', 'Dog', 5, 'Poodle', 'Male', 'Sold'),
('Bailey', 'Rabbit', 7, 'Bulldog', 'Female', 'Under Treatment'),
('Scout', 'Cat', 2, 'Labrador', 'Female', 'Under Treatment'),
('Scout', 'Cat', 1, 'Beagle', 'Female', 'Under Treatment'),
('Dexter', 'Rabbit', 8, 'Siamese', 'Male', 'Under Treatment'),
('Ruby', 'Bird', 3, 'Siamese', 'Male', 'Under Treatment'),
('Hunter', 'Dog', 10, 'Labrador', 'Female', 'Under Treatment'),
('Ellie', 'Rabbit', 7, 'Beagle', 'Male', 'Sold'),
('Dexter', 'Bird', 3, 'Golden Retriever', 'Male', 'Available'),
('Harper', 'Bird', 9, 'Golden Retriever', 'Female', 'Sold'),
('Cleo', 'Cat', 4, 'Siamese', 'Male', 'Sold'),
('Finn', 'Cat', 10, 'Poodle', 'Male', 'Available'),
('Teddy', 'Cat', 3, 'Beagle', 'Male', 'Available'),
('Chloe', 'Bird', 10, 'Parrot', 'Male', 'Available'),
('Rosie', 'Bird', 2, 'Labrador', 'Male', 'Available'),
('Chloe', 'Bird', 5, 'Holland Lop', 'Female', 'Sold'),
('Blue', 'Cat', 8, 'Poodle', 'Female', 'Under Treatment'),
('Koda', 'Cat', 9, 'Labrador', 'Female', 'Sold'),
('Blue', 'Cat', 5, 'Bulldog', 'Female', 'Sold');
